table Dim_Date
	lineageTag: e85c79ec-2d2c-4028-95fe-4bfb62cf58e8

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 32fa394c-1952-4a2d-b875-104481b07c9e
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 4645be31-2bcc-4b02-9e1d-e26d1a4b1614
			defaultHierarchy: LocalDateTable_ff3bb01f-d81e-4ed4-b9b5-c4effbf4dbf4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5840dc01-4b65-4783-97b6-67f8e8e572a7
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 679ff72e-a3fd-41af-b158-dbe763d3b53a
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: cdb9c142-406b-4a6b-a0e5-2b6561c8d81f
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sasth\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", type text}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"sales_amount", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates"),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates1",{{"date", Order.Ascending}}),
				    #"Inserted Year" = Table.AddColumn(#"Sorted Rows", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([date]), Int64.Type)
				in
				    #"Inserted Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

