table Fact_Sales
	lineageTag: ff753db1-6b70-4f5a-8a46-d052b890d737

	measure 'Total Sales' =
			
			SUM ( Fact_Sales[sales_amount] )
		lineageTag: febfab82-7554-40d7-8d82-1097af6b13be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: string
		lineageTag: 7d48f41b-dc22-4342-88e2-2e3f8a297b7b
		summarizeBy: none
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eef9e75d-897b-4186-9095-acd96464ce97
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: e39bc951-a573-46dd-9690-82f055709c55
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 817103f1-37b6-4605-b93e-ce8af4fdf0fd
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 6df01236-9d1d-4d28-b298-99724f70434e
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 86329b2d-3949-43ea-94ce-b329b1b247f8
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 92cfef0f-6602-4c37-b91d-75b7dc8a4e3c
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 15f3060e-d31b-4c10-8e1f-5097a34b6472
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_amount
		dataType: double
		lineageTag: 2b39d9be-b273-416a-8a0a-05ed6592c39d
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductKey
		dataType: string
		lineageTag: 0ccd6db3-e84a-4725-ab8c-cc7b7cd9b7d8
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sasth\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", type text}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"sales_amount", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "ProductKey", each [category] & "|" & [item])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

